### 1. Import das bibliotecas e definição da função de leitura

In [1]:
import requests
import pandas as pd

def read_ckan_sql(resource_id):
    url = "https://dados.uffs.edu.br/api/3/action/datastore_search_sql"

    limit = 1000
    offset = 0
    all_records = []

    while True:
        sql = f'''
        SELECT *
        FROM "{resource_id}"
        LIMIT {limit}
        OFFSET {offset}
        '''

        response = requests.get(url, params={"sql": sql})
        data = response.json()

        records = data["result"]["records"]

        if not records:
            break

        all_records.extend(records)
        offset += limit

        print(f"Baixados: {offset}")

    df = pd.DataFrame(all_records)
    return df

### 2. Passa o id dos dados pra função de leitura, e transforma o resultado em um dataframe pandas

In [2]:
df_contratos = read_ckan_sql("30ce5339-c4fe-4b92-b0b5-e5c9901ef3f9")
print("Número de registros:", len(df_contratos))

Baixados: 1000
Número de registros: 561

### 3. Mostra os 5 primeiros registros

In [3]:
df_contratos.head()

,_id,_full_text,ano,numero,objeto,modalidade_licitacao,parcelamento_contrato,data_assinatura,data_publicacao,data_inicio,...,valor_original,valor_acumulado,saldo,tipo_contrato,subtipo_contrato,licitacao_correspondente,situacao,nome_fornecedor,continuado,data_atualizacao
0,1,"'-02':68,71,74 '-04':101 '-06':78,102 '-10':77...",2026,14,EXECUÇÃO DA OBRA DO CENTRO DE ACOLHIMENTO DE ...,CONCORRÊNCIA,NÃO PARCELADO,2026-02-13,2026-02-24,2026-02-13,...,3888345.28,3888345.28,3888345.28,DESPESA,OBRAS E SERVIÇOS DE ENGENHARIA,CC-90001/2025,ABERTO,M A GRABIN & CIA LTDA,NÃO,2026-04-06T02:30:15.276367
1,2,"'-02':66,69,72 '-04':99 '-06':76,100 '-10':75 ...",2026,13,EXECUÇÃO DA OBRA DO CENTRO DE ACOLHIMENTO DE ...,CONCORRÊNCIA,NÃO PARCELADO,2026-02-13,2026-02-24,2026-02-13,...,2019702.75,2019702.75,2019702.75,DESPESA,OBRAS E SERVIÇOS DE ENGENHARIA,CC-90001/2025,ABERTO,M A GRABIN & CIA LTDA,NÃO,2026-04-06T02:30:15.276367
2,3,"'-02':67,70,73 '-04':100 '-06':77,101 '-10':76...",2026,12,EXECUÇÃO DA OBRA DO CENTRO DE ACOLHIMENTO DE ...,CONCORRÊNCIA,NÃO PARCELADO,2026-02-13,2026-02-24,2026-02-13,...,2087666.30,2087666.30,2087666.30,DESPESA,OBRAS E SERVIÇOS DE ENGENHARIA,CC-90001/2025,ABERTO,SCW CONSTRUÇÕES E SERVIÇOS LTDA,NÃO,2026-04-06T02:30:15.276367
3,4,"'-01':40,46,49 '-02':43 '-04':44,74 '-06':75 '...",2026,11,"PRESTAÇÃO DE SERVIÇOS DE PLANEJAMENTO, ORGANIZ...",DISPENSA DE LICITAÇÃO,NÃO PARCELADO,2026-01-30,2026-02-04,2026-01-30,...,159000.00,159000.00,159000.00,DESPESA,CONCURSOS,DL-1/2026,ABERTO,"INSTITUTO DE ACESSO À EDUCAÇÃO, CAPACITAÇÃO PR...",NÃO,2026-04-06T02:30:15.276367
4,11,"'-01':41,44,47,50 '-04':70 '-06':71 '-14':51 '...",2026,4,"AQUISIÇÃO DE RECARGAS DE GASES ESPECIAIS, MEDI...",PREGÃO,NÃO PARCELADO,2026-01-15,2026-01-20,2026-01-15,...,13201.00,13201.00,13201.00,DESPESA,AQUISIÇÃO DE BENS/MATERIAIS/EQUIPAMENTOS,PR-90039/2025,ABERTO,ECOLÓGICA OXIGÊNIO LTDA,SIM,2026-04-06T02:30:15.276367

### 4. Leitura do dicionário de dados do arquivo

In [4]:
df_dicionario_dados = read_ckan_sql("d8022fcc-4426-4503-9fb0-b0136b7203ed")
print("Número de registros:", len(df_dicionario_dados))

Baixados: 1000
Número de registros: 22

### 5. Mostra os registros

In [5]:
df_dicionario_dados

,_id,_full_text,coluna,tipo,rotulo,descricao
0,1,"'ano':1,3,4 'cadastr':10 'contrat':8 'int4':2",ano,int4,Ano,Ano em que o contrato foi cadastrado.
1,2,'automat':8 'contrat':6 'ger':7 'int4':2 'nume...,numero,int4,Número,"Número do contrato, gerado automaticamente pel..."
2,3,"'contrat':7 'descrev':8 'objet':1,3,5 'text':2...",objeto,text,Objeto,O objeto do contrato descreve do que ele se tr...
3,4,"'complet':8 'licit':6,12 'licitaca':2 'modal':...",modalidade_licitacao,text,Modalidade de Licitação,Nome completo da modalidade de licitação.
4,5,"'anu':21 'camp':23 'contrat':2,6,8 'form':26 '...",parcelamento_contrato,text,Parcelamento do Contrato,Um contrato pode ser de parcela única(não parc...
5,6,"'assinatur':2,6,9 'contrat':11 'dat':1,3,4,7",data_assinatura,date,Data de Assinatura,Data de assinatura do contrato.
6,7,"'contrat':11 'dat':1,3,4,7 'oficial':14 'publi...",data_publicacao,date,Data de Publicação,Data em que o contrato foi publicado oficialme...
7,8,"'contrat':11 'dat':1,3,4,7 'inic':13 'inici':2...",data_inicio,date,Data de Início,Data em que o contrato foi iniciado.
8,9,"'assinatur':20 'contrat':15 'dat':1,4,5,9 'enc...",data_fim_prevista,date,Data de Fim Prevista,"Data prevista para o encerramento do contrato,..."
9,10,"'contrat':13 'dias':1,4,9 'int4':3 'quantidad'...",dias_vigencia,int4,Dias de Vigência,Quantidade de dias de vigência do contrato.
10,11,"'andament':23 'contrat':13,21 'dat':1,4,5,9 'e...",data_finalizacao_efetiva,date,Data de Finalização Efetiva,Data em que o contrato foi oficialmente encerr...
11,12,"'alter':22 'anual':32 'atual':2,5,42 'camp':12...",valor_atual,numeric,Valor Atual,"Para contratos de parcela única, esse campo te..."
12,13,"'acord':46 'anual':34 'assinatur':26,50 'cad':...",valor_original,numeric,Valor Original,"Para contratos de parcela única, esse campo te..."
13,14,"'acumul':2,5 'anual':33 'camp':12,35 'contrat'...",valor_acumulado,numeric,Valor Acumulado,"Para contratos de parcela única, esse campo te..."
14,15,"'atual':23 'autoincrement':9 'camp':11,30 'con...",saldo,numeric,Saldo,"Para contratos de despesa e autoincremento, es..."
15,16,"'antemã':56 'autoincrement':15,23,66 'cad':82 ...",tipo_contrato,text,Tipo de Contrato,"Os contratos podem ser de Receita, Despesa e A..."
16,17,"'camp':8 'contrat':2,6,13 'descrev':9 'etc':23...",subtipo_contrato,text,Subtipo de Contrato,Esse campo descreve no que o contrato será uti...
17,18,"'/ano':15 'consegu':22 'correspondent':2,5 'có...",licitacao_correspondente,text,Licitação Correspondente,"Código identificador da licitação, formado por..."
18,19,'andament':10 'diz':4 'encerr':14 'projet':7 '...,situacao,text,Situação,Diz de o projeto está em andamento ou se já en...
19,20,"'complet':8 'fornecedor':2,6,10 'físic':16 'ju...",nome_fornecedor,text,Nome do Fornecedor,"Nome completo do fornecedor, o qual pode ser p..."
20,21,"'continu':1,3,9,13 'ininterrupt':14 'prestaçã'...",continuado,text,Continuado?,O serviço é de prestação continuada? Serviços ...
21,22,"'ano':20 'ano-mês-d':19 'atualiz':6,9 'atualiz...",data_atualizacao,timestamp,Data de Atualização,"Data de atualização do conjunto de dados, form..."

### Funções úteis

In [8]:
# 1. Função para formatar o número no padrão moeda do Brasil
from pandas.io.formats.style import Styler
def formatar_moeda_br(valor):
    if pd.isna(valor):
        return "R$ 0,00"
    
    # Formata com 2 casas decimais no padrão americano (ex: 1,234,567.89)
    valor_str = f"{valor:,.2f}"
    
    # Troca a vírgula por um 'X' temporário, o ponto por vírgula, e o 'X' por ponto
    valor_br = valor_str.replace(",", "X").replace(".", ",").replace("X", ".")
    
    return f"R$ {valor_br}"

## Análises iniciais

### Top 10 maiores contratos firmados

In [9]:
# Converte as colunas financeiras para float
cols_financeiras = ['valor_original', 'valor_atual', 'valor_acumulado', 'saldo']
for col in cols_financeiras:
    df_contratos[col] = pd.to_numeric(df_contratos[col], errors='coerce')

# Filtra as colunas mais importantes e ordena pelos maiores valores acumulados
top_contratos = df_contratos[['numero', 'ano', 'nome_fornecedor', 'objeto', 'tipo_contrato', 'valor_acumulado', 'situacao']]
top_contratos = top_contratos.sort_values(by='valor_acumulado', ascending=False)

top_10_contratos = top_contratos.head(10)

# 3. Aplicando a formatação visual usando o Styler
top_10_contratos.style.format({
    'valor_acumulado': formatar_moeda_br
})

In [10]:
# 1. Garante que as colunas são numéricas
df_contratos['valor_atual'] = pd.to_numeric(df_contratos['valor_atual'], errors='coerce')
df_contratos['valor_original'] = pd.to_numeric(df_contratos['valor_original'], errors='coerce')

# 2. Cria a coluna de Custo com Aditivos (Diferença)
df_contratos['custo_aditivos'] = df_contratos['valor_atual'] - df_contratos['valor_original']

# 3. Filtra apenas contratos que tiveram aumento (aditivo > 0)
df_com_aditivo = df_contratos[df_contratos['custo_aditivos'] > 0].copy()

# 4. Seleciona as colunas de interesse para a análise
colunas_analise = [
    'numero', 'ano', 'nome_fornecedor', 'objeto', 
    'parcelamento_contrato', 'valor_original', 'valor_atual', 'custo_aditivos'
]
df_com_aditivo = df_com_aditivo[colunas_analise]

# 5. Ordena para ver os maiores "estouros" de orçamento primeiro
df_com_aditivo = df_com_aditivo.sort_values(by='custo_aditivos', ascending=False)

# 6. Exibe os 10 contratos com maiores aditivos, formatando como moeda
df_com_aditivo.head(10).style.format({
    'valor_original': formatar_moeda_br,
    'valor_atual': formatar_moeda_br,
    'custo_aditivos': formatar_moeda_br
})